#Default cluster name used when no cluster name is specified (e.g. joining a cluster)
#cluster.name: elasticsearch

#Default node name used for the shell when creating a node (either NodeClient or LocalNode)
#node.name: elasticshell

#Default host and port used when no host and port are specified (e.g. creating a TransportClient)
#transport:
#  host: localhost
#  port: 9300

#Startup script that will be run while starting up the shell
#Will be looked up within the user home directory if not set
#It can contain whatever command that's valid within the shell itself
#startup.script: .elasticshellrc.js

#Maximum number of suggestions that will be shown in the shell
#suggestions.max: 100

#Enables playground mode: automatically creates a local node at startup and a client connected to it
#playground.mode: false